### ISSUE TITLE
/dev/urandom remains open after thread is destroyed

### ISSUE THREAD

**Issue by asciinen** [sionescu/bordeaux-threads#75] opened 2020-07-03 23:32 UTC
On SBCL running on Linux, every time a thread is created, /dev/urandom is opened. It remains open even after the thread has returned. Therefore, this eventually produces an error (too many open files, cannot open /dev/random) if threads are constantly created and destroyed.

For example:

`(loop repeat 100 do (bt:make-thread #'(lambda ())))`

will leave the SBCL process with 100 open /dev/urandom files (as shown by "lsof -c sbcl").

This does not happen if sb-thread:make-thread is used instead of bt:make-thread.

**Comment by sionescu** [comment] 2020-07-04 00:47
What version of SBCL is that ? I cannot reproduce that on SBCL 2.0.6.

**Comment by asciinen** [comment] 2020-07-04 07:05
SBCL 2.0.5 (the current one on Arch Linux).

Thanks for the answer, I'll try with 2.0.6

**Comment by asciinen** [comment] 2020-07-04 07:45
This behavior does not depend on the version of SBCL after all (I checked 2.0.5 and 2.0.6), but on the "ironclad" library being loaded. At least, its current quicklisp version, which is ironclad-v0.49.

**Comment by sionescu** [comment] 2020-07-04 07:51
On Sat, 2020-07-04 at 00:45 -0700, asciinen wrote:
> This behavior does not depend on the version of SBCL after all (I
> checked 2.0.5 and 2.0.6), but on the "ironclad" library being loaded.
> At least, its current quicklisp version, which is ironclad-v0.49.

Then I suggest you open an bug on the Ironclad tracker.

Close #75

-- 
Stelian Ionescu a.k.a. fe[nl]ix
Quidquid latine dictum sit, altum videtur.

**Comment by asciinen** [comment] 2020-07-04 07:57
Well, perhaps. On the other hand, ironclad seems to work fine, as long as I use sb-threads instead of bordeaux-threads.

**Comment by asciinen** [comment] 2020-07-04 08:06
I think you are right that ironclad is the culprit. The behavior does not occur with ironclad-v0.48, only with ironclad-v0.49

**Comment by sionescu** [comment] 2020-07-04 20:43
It looks like this problem should be fixed in version 0.50, which was released a few days ago.

**Comment by asciinen** [comment] 2020-07-04 20:49
> It looks like this problem should be fixed in version
> 0.50, which was released a few days ago.

Yes, I checked that it was already solved in the latest
github commit, so I did not file any report.

P.

**Closed** 2020-07-16 22:36 UTC
