### ISSUE TITLE
Load error on Lispworks 7.0.0

### ISSUE THREAD

**Issue by jaredcdavis** [sionescu/bordeaux-threads#15] opened 2016-01-11 14:17 UTC
On Lispworks 7.0.0 I'm running into a problem loading bordeaux-threads via Quicklisp.

Example output:

    ; Loading "bordeaux-threads"
    [package alexandria.0.dev]........................
    [package bordeaux-threads]..

    Backtrace [because of error: Undefined function
    DEFINE-CONDITION-WAIT-COMPILER-MACRO called with arguments ().]:

Here's a script for reproducing the error:

```
#!/bin/sh

set -e

DIR=`pwd`

echo "Downloading Quicklisp"
wget https://beta.quicklisp.org/quicklisp.lisp

echo "Setting up new asdf-home"
rm -rf asdf-home inst
mkdir asdf-home
export XDG_CONFIG_HOME=$DIR/asdf-home/config
export XDG_DATA_HOME=$DIR/asdf-home/data
export XDG_CACHE_HOME=$DIR/asdf-home/cache

echo "Configuring Quicklisp"
lispworks -init - <<EOF
(load "quicklisp.lisp")
(quicklisp-quickstart:install :path "$DIR/inst")
(quit)
EOF

echo "Running test"
lispworks -init - <<EOF
(load "inst/setup.lisp")
(ql:quickload "bordeaux-threads")
(quit)
EOF
```

**Comment by sionescu** [comment] 2016-01-11 14:43
Unfortunately I cannot reproduce this because I don't have a Lispworks licence.

**Comment by macdavid313** [comment] 2016-01-12 11:59
please clone it in your `local-project` directory then try again @jaredcdavis

**Comment by jaredcdavis** [comment] 2016-01-12 15:04
Looks like that fixed it, thanks!

**Comment by fourier** [comment] 2016-01-19 22:00
I'm experiencing the same problem. The local version has fixed it however as well. I'm wandering will it be fixed by the next release of quicklisp packages.

**Comment by sionescu** [comment] 2016-01-19 23:30
I tagged release 0.8.5. It should appear in the next Quicklisp snapshot.

**Closed by sionescu** 2016-01-19 23:30 UTC
