### ISSUE TITLE
Portable read-write-locks

### ISSUE THREAD

**Issue by astrangeguy** [sionescu/bordeaux-threads#93] opened 2021-05-11 12:20 UTC
Hi there,

both Clozure CL ([natively](https://ccl.clozure.com/manual/chapter7.7.html#f_make-read-write-lock)) and ABCL (via Java [ReadWriteLock](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReadWriteLock.html)) have readers-writer-locks, and on most other implementations these semantics could be provided via locks, semaphores and atomic-incf on struct/class slots.

Readers-writer-locks with writer priority and lockless reader semantics if no writers are present are extremely useful in multi-threaded applications when working with complex data that has to be in a consistent state when reading and is irregularly updated.

I would like to contribute an implementation with documentation and tests if there is any interest.

**Comment by sionescu** [comment] 2022-01-04 00:57
Closing as duplicate of #77. Reader/writer locks are still on the roadmap for APIv2.

**Closed by sionescu** 2022-01-04 00:57 UTC
