### ISSUE TITLE
error when compiling to lib on ecl

### ISSUE THREAD

**Issue by jesseoff** [sionescu/bordeaux-threads#79] opened 2020-08-01 00:02 UTC
I can't build bordeaux-threads as a library.

I think, however, its asdf's problem so I submitted an issue there, but FYI:

https://gitlab.common-lisp.net/asdf/asdf/-/issues/39

```console
root@raspberrypi:~/quicklisp/local-projects/ts-fpga# make bordeaux-threads--all-systems.a
ecl -norc \
    -eval '(load "asdf")' \
    -eval '(load "./ql-bundle/bundle.lisp")' \
    -eval '(push "./" asdf:*central-registry*)' \
    -eval "(asdf:operate 'asdf:monolithic-lib-op :bordeaux-threads)" \
    -eval '(quit)'
;;; Loading #P"/root/quicklisp/local-projects/ts-fpga/asdf.fas"
An error occurred during initialization:
The function %MAKE-LOCK is undefined..
make: *** [Makefile:40: bordeaux-threads--all-systems.a] Error 1
```

**Comment by sionescu** [comment] 2022-01-04 00:58
Does this still happen ?

**Comment by sionescu** [comment] 2022-01-09 22:03
Closing because I can't reproduce with ECL 21.2.1 and ASDF 3.3.5.6

**Closed by sionescu** 2022-01-09 22:03 UTC
Labels: host error
